image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

# note: on macOS the binary is built using Python 3.7 (installed via Homebrew), because
# the shipped Python lacks libraries PyInstaller needs.
stack: python 3.6

# note: 32 bit linux binary is build using docker
for:
-
  matrix:
    only:
      - image: Ubuntu

  services:
    - docker

environment:
  PY_DIR: C:\Python36-x64

init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

build: off

artifacts:
  - path: "dist\\safety-win-32.exe"
    name: "safety-win-32.exe"
  - path: "dist\\safety-win-64.exe"
    name: "safety-win-64.exe"
  - path: "dist\\safety-linux-32"
    name: "safety-linux-32"
  - path: "dist\\safety-linux-64"
    name: "safety-linux-64"
  - path: "dist\\safety-macos-64"
    name: "safety-macos-64"

install:
  - "python --version"
  - "python appveyor.py install"

test_script:
  - "python appveyor.py test"
  - "python appveyor.py dist"


deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: dDJgAsevLfBL9BKNuCKpbFhB5rlfbefw696Xe6Na8BhHabwoGYcg8FydNpppnKzX
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
